# ------------------------------------------------------------------------------
# Generate a data flow manifest
# Then open a PR to incorporate them into the repo
# ------------------------------------------------------------------------------
name: generate-dataflow-manifest
on:
  workflow_dispatch:
    inputs:
      data_model:
        description: URL to a jsonld data model file
        required: true
      community_dir:
        description: Community directory
        required: true

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: 'renv'

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2

      - name: Write environment variables
        shell: bash
        run: |
          echo 'data_model=${{ inputs.data_model }}' >> $GITHUB_ENV
          echo 'community_dir=${{ inputs.community_dir }}' >> $GITHUB_ENV

      - name: Generate Data Flow manifest
        shell: Rscript {0}
        run: print(list.files())
