# ------------------------------------------------------------------------------
# Generate a data flow manifest
# Then open a PR to incorporate them into the repo
# ------------------------------------------------------------------------------
name: generate-dataflow-manifest
on:
  workflow_dispatch:
    inputs:
      config_dir:
        description: Directory that contains dfa_config.json (ex. "Demo")
        required: true
jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      SCHEMATIC_BASE_URL: https://schematic.api.sagebionetworks.org
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pip libicu-dev libcurl4-openssl-dev

      - name: Install R packages
        run: |
          options(repos = c(REPO_NAME = "https://packagemanager.rstudio.com/all/__linux__/xenial/latest", 
            getOption("repos")))
          install.packages(c("stringi", "jsonlite", "dplyr", "remotes", "curl","httr"))
          remotes::install_github("Sage-Bionetworks/dfamodules", ref = "dev")
        shell: Rscript {0}

      - name: Generate Data Flow manifest and Submit to Synapse
        shell: Rscript {0}
        run: |
          config_path <- file.path("${{ env.config_dir }}", "dfa_config.json")

          dfa_config <- jsonlite::read_json(config_path)

          dataflow_manifest <- tryCatch(
            {
              dfamodules::generate_dataflow_manifest(
                asset_view = dfa_config$dcc$synapse_asset_view,
                schema_url = dfa_config$dcc$data_model_url,
                access_token = "${{ secrets.SYNAPSE_PAT }}",
                na_replace = "",
                base_url = "${{ env.SCHEMATIC_BASE_URL }}")
            },
            error = function(e) {
              message(e)
              stop("ERROR: Data Flow manifest generation has failed")
            }
          )

          message("Successfully generated Data Flow Manifest")

          write.csv(
            x = dataflow_manifest,
            file = "synapse_storage_manifest_dataflow.csv",
            row.names = FALSE
          )

          submit_id <- try(
            {
              dfamodules::model_submit(
                data_type = "DataFlow",
                asset_view = dfa_config$dcc$synapse_asset_view,
                dataset_id = dfa_config$dcc$manifest_dataset_id,
                file_name = "synapse_storage_manifest_dataflow.csv",
                access_token = "${{ env.SYNAPSE_PAT }}",
                restrict_rules = TRUE,
                manifest_record_type = "table_and_file",
                base_url = "${{ env.SCHEMATIC_BASE_URL }}",
                schema_url = dfa_config$dcc$data_model_url,
                use_schema_label = TRUE)
            },
            silent = TRUE
          )

          if (inherits(submit_id, "try-error")) {
            stop("ERROR: Manifest submission failed")
          } else {
            synapse_url <- file.path("https://www.synapse.org/Synapse:", dfa_config$dcc$manifest_dataset_id)
            message("Successfully submitted manifest to ", synapse_url)
          }
